# Generated by Django 6.0.6 on 2026-07-02 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0002_alertstate_is_suppressed'),
        ('barangays', '0004_barangay_distance_to_river_km_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], help_text='Barangay category at the moment of the event.', max_length=10)),
                ('kind', models.CharField(choices=[('entered', 'Entered critical'), ('renotify', 'Re-notified (still critical)'), ('all_clear', 'All clear'), ('broadcast', 'Operator broadcast')], max_length=10)),
                ('source', models.CharField(choices=[('automated', 'Automated (pipeline)'), ('operator', 'Operator')], default='automated', max_length=10)),
                ('score', models.FloatField(blank=True, help_text='Hazard score (0-100); null for broadcasts.', null=True)),
                ('recipients', models.PositiveIntegerField(default=0, help_text='Subscribers reached across all channels.')),
                ('suppressed', models.BooleanField(default=False, help_text='Transition occurred but automated dispatch was muted (operator suppression), so no one was notified.')),
                ('dispatch_key', models.CharField(db_index=True, help_text='Ties back to NotificationLog rows.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('barangay', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='barangays.barangay')),
                ('triggered_by', models.ForeignKey(blank=True, help_text='Operator who sent a broadcast; null for automated events.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['barangay', '-created_at'], name='alert_alert_baranga_b2d5dd_idx')],
            },
        ),
    ]
