# Generated by Django 6.0.6 on 2026-07-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0003_alertevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_category', models.CharField(choices=[('high', 'High and above'), ('critical', 'Critical only')], default='critical', help_text='Minimum risk category that triggers a resident alert.', max_length=10)),
                ('renotify_interval_minutes', models.PositiveIntegerField(default=60, help_text='Cooldown before re-notifying a still-triggered barangay.')),
                ('send_all_clear', models.BooleanField(default=True, help_text='Notify when a barangay drops out of the trigger band.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
