# Generated by Django 6.0.6 on 2026-07-03 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood_events', '0002_floodevent_ended_at_floodevent_people_affected_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoDetectConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('threshold_category', models.CharField(choices=[('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='high', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='floodevent',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floodevent',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_flood_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='floodevent',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='floodevent',
            name='is_confirmed',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='floodevent',
            name='source_kind',
            field=models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto-detected')], db_index=True, default='manual', max_length=10),
        ),
        migrations.CreateModel(
            name='FloodEventChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('confirmed', 'Confirmed'), ('resolved', 'Resolved'), ('deleted', 'Deleted'), ('restored', 'Restored')], default='updated', max_length=10)),
                ('field', models.CharField(blank=True, max_length=50)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('flood_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='flood_events.floodevent')),
            ],
            options={
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['flood_event', '-changed_at'], name='flood_event_flood_e_0de2d6_idx')],
            },
        ),
    ]
