# Generated by Django 6.0.6 on 2026-07-03 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood_events', '0003_autodetectconfig_floodevent_confirmed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='floodevent',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_flood_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='floodevent',
            name='source_type',
            field=models.CharField(choices=[('operator', 'Operator'), ('third_party', '3rd-party report')], default='third_party', max_length=12),
        ),
        migrations.AlterField(
            model_name='floodevent',
            name='water_depth_m',
            field=models.FloatField(blank=True, help_text='Peak flood depth in feet.', null=True),
        ),
    ]
