# Generated by Django 6.0.6 on 2026-07-01 01:02

import django.db.models.deletion
import risk_score.models.risk_config
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barangays', '0003_rename_land_height_barangay_land_height_max_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('weights', models.JSONField(default=risk_score.models.risk_config.default_weights)),
                ('thresholds', models.JSONField(default=risk_score.models.risk_config.default_thresholds)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('category', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('breakdown', models.JSONField(default=dict)),
                ('is_degraded', models.BooleanField(default=False)),
                ('computed_at', models.DateTimeField(db_index=True)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_scores', to='barangays.barangay')),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scores', to='risk_score.riskconfig')),
            ],
            options={
                'ordering': ['-computed_at'],
                'indexes': [models.Index(fields=['barangay', '-computed_at'], name='risk_score__baranga_1b748f_idx')],
            },
        ),
    ]
