# Generated by Django 6.0.6 on 2026-07-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalToggles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Show a maintenance banner; a soft signal to clients.')),
                ('announcement_banner', models.CharField(blank=True, help_text='System-wide banner text shown in the console.', max_length=280)),
                ('broadcast_enabled', models.BooleanField(default=True, help_text='Kill-switch for operator broadcasts.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(default='FRACAS', max_length=120)),
                ('system_title', models.CharField(default='FRACAS Console', max_length=120)),
                ('contact_number', models.CharField(blank=True, max_length=40)),
                ('alert_footer', models.CharField(blank=True, help_text='Signature appended to alert/broadcast messages (e.g. — Zamboanga City DRRMO).', max_length=160)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rainfall_retention_days', models.PositiveIntegerField(default=30)),
                ('risk_score_retention_days', models.PositiveIntegerField(default=90)),
                ('flood_event_purge_grace_hours', models.PositiveIntegerField(default=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
