# Generated by Django 6.0.6 on 2026-07-01 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_device_notificationpreference_phoneotp_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-created_at']},
        ),
    ]
