# Generated by Django 6.0.6 on 2026-07-02 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_device_options_alter_subscription_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_operator',
            field=models.BooleanField(default=False, help_text="DRRMO operator: can run the web console (GIS, history, broadcasts, monitoring) but is deliberately kept OUT of the Django admin site. Admin-site access is Django's `is_staff`; operators are non-staff."),
        ),
    ]
