# Generated by Django 6.0.6 on 2026-07-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_terms_accepted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_registration_enabled', models.BooleanField(default=True, help_text='Allow the public app to start new resident registrations.')),
                ('otp_ttl_minutes', models.PositiveIntegerField(default=10, help_text='How long a phone verification code stays valid.')),
                ('terms_version', models.CharField(default='1', help_text='Bumping this can force residents to re-accept the terms.', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
